### ISSUE TITLE
No native build was found for platform=linux arch=arm64

### ISSUE THREAD

**Issue by buddingworld** [rejetto/thumbnails#1]
Sep 26 17:12:58 armbian npx[20619]: plugin error: thumbnails: No native build was found for platform=linux arch=arm64 runtime=node abi=115 uv=1 armv=8 libc=glibc node=20.7.0
Sep 26 17:12:58 armbian npx[20619]:     loaded from: /root/.hfs/plugins/thumbnails/node_modules/classic-level

how can I deal with this?I've tried all I can do.

**Comment by rejetto** [comment]
i'll let you know

**Comment by rejetto** [comment]
i made some deep changes and produced a new version of this plugin, version 2, which supports linux-arm64.
I couldn't test it, tho, so cross fingers. 🙃
The new version requires another plugin, "sharp", so if you don't install it first, you'll get this an error trying to update
<img width="304" alt="image" src="https://github.com/rejetto/thumbnails/assets/1367199/9209ffd4-e7d5-416e-9ea9-45ab0ddd7a55">

Please let me know if everything is ok.

**Comment by rejetto** [comment]
thakns for reporting!
i was using an outdated module.
update sharp now, and let me know

**Comment by buddingworld** [comment]
> thanks for reporting! i was using an outdated module. update sharp now, and let me know

thanks very much!it works now!i am happy to use this.thx again!
